-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 25, 2022 at 04:55 PM
-- Server version: 10.5.15-MariaDB-log
-- PHP Version: 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zppssi_blasports`
--

-- --------------------------------------------------------

--
-- Table structure for table `questions_1`
--

CREATE TABLE `questions_1` (
  `Type` varchar(8) CHARACTER SET utf8 DEFAULT NULL,
  `F1` varchar(255) NOT NULL,
  `Q1` varchar(9) CHARACTER SET utf8 DEFAULT NULL,
  `Q2` varchar(142) CHARACTER SET utf8 DEFAULT NULL,
  `ideas` varchar(1262) CHARACTER SET utf8 DEFAULT NULL,
  `F1_text` varchar(255) NOT NULL,
  `Q1_text` varchar(38) CHARACTER SET utf8 DEFAULT NULL,
  `Q2_text` varchar(16) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `questions_1`
--

INSERT INTO `questions_1` (`Type`, `F1`, `Q1`, `Q2`, `ideas`, `F1_text`, `Q1_text`, `Q2_text`) VALUES
('Training', '', 'Physical', 'I just finished a super-hard badminton training but it was worth it. I\'m a bit tired and I hope this weekend I can rest well.', 'I had a great training session!\r\nTough workout, but feeling accomplished!\r\nFinished my training and feeling proud!\r\nHard training session, but it was worth it!\r\nBadminton training was tough, but I\'m feeling good!\r\nFinished my training and feeling excited for the weekend!\r\nTraining was tough but I\'m feeling energized!\r\nFinished my training and feeling motivated!\r\nTraining was hard, but I\'m ready for more!\r\nFinished my training and feeling proud!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'I won’t lie — physical training is tough, but it’s the best therapy for me.', 'I love how physical training makes me feel — strong and capable.\r\nPhysical training is definitely challenging, but it\'s worth it.\r\nTraining is hard, but it\'s the best way to stay healthy and happy.\r\nI\'m grateful for physical training because it keeps me healthy and strong.\r\nPhysical training is essential for my well-being.\r\nI\'m so grateful that physical training is a part of my life.\r\nPhysical training is hard, but it\'s so worth it in the end.\r\nI love how physical training makes me feel — strong, capable, and happy.\r\nPhysical training is definitely a challenge, but it\'s worth it.\r\nTraining is hard, but it\'s the best way to stay healthy and happy.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'Hardworking can make dreams come true', 'If you want something bad enough and are willing to put in the work, you can make your dreams come true.\r\nNo matter how big your dreams may seem, if you\'re willing to work hard for them, they can become a reality.\r\nHard work is the key to making your dreams come true.\r\nDreams don\'t come true without a lot of hard work.\r\nNothing worth having comes easy. If you want your dreams to come true, you\'re going to have to work for it.\r\nThe only way to achieve your dreams is through hard work.\r\nIf you\'re willing to put in the hard work, you can make your dreams a reality.\r\nSuccess doesn\'t come easy - it takes a lot of hard work to achieve your dreams.\r\nYou have to be willing to work hard if you want your dreams to come true.\r\nHard work is the only way to make your dreams a reality.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'I might be tired but I will never give up. World class winners never quit and quitters never win!', 'Don\'t give up, no matter how tired you are. World class winners never quit and quitters never win!\r\nYou might be tired, but don\'t give up. Winners never quit and quitters never win!\r\nKeep going, no matter how tired you are. Winners never quit and quitters never win!\r\nNever give up, no matter how tired you are. Winners never quit and quitters never win!\r\nDon\'t let fatigue stop you. Winners never quit and quitters never win!\r\nDon\'t give up, no matter how exhausted you are. Winners never quit and quitters never win!\r\nYou might be tired, but don\'t give up. Winners never quit and quitters never win!\r\nKeep going, no matter how tired you are. Winners never quit and quitters never win!\r\nNever give up, no matter how tired you are. Winners never quit and quitters never win!\r\nDon\'t let fatigue stop you. Winners never quit and quitters never win!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'What a great day, I\'m quite exhausted but it\'s always worth it.', 'What a great day! I\'m exhausted but it was worth it.\r\nI had a great day! I\'m exhausted but it was worth it.\r\nI had a great day! I\'m tired but it was worth it.\r\nI had a great day! I\'m worn out but it was worth it.\r\nI had a great day! I\'m beat but it was worth it.\r\nI had a great day! I\'m pooped but it was worth it.\r\nI had a great day! I\'m spent but it was worth it.\r\nI had a great day! I\'m wiped but it was worth it.\r\nI had a great day! I\'m drained but it was worth it.\r\nI had a great day! I\'m exhausted and it was worth it.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'Just finished an exhausting yet rewarding badminton training. I like the smell of physical fitness.', 'Just finished a great badminton training! Feeling really fit now.\r\nFinished a tough badminton training session- feeling great and ready for more!\r\nTough badminton training done- feeling awesome and motivated!\r\nBadminton training was awesome- feeling really fit and motivated now!\r\nJust completed an awesome badminton training- feeling great and motivated!\r\nFinished a great badminton training- feeling really fit and motivated!\r\nBadminton training was great- feeling really fit and motivated now!\r\nJust completed an intense badminton training- feeling great and motivated!\r\nFinished an awesome badminton training- feeling really fit and motivated!\r\nBadminton training was fantastic- feeling really fit and motivated now!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'I am a badminton player, today I finished the physical training! Keep up!', 'I am a badminton player! I had a great physical training today! Keep it up!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I am always looking for ways to improve my game! Today\'s physical training was great for me!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I need to be in top condition! Today\'s physical training was great for me!\r\n\r\nI am a badminton player and I need to be in top condition! I had a great physical today!\r\n\r\nI am a badminton player and I had a great physical training today! I am always looking for ways to improve my game!\r\n\r\nI am a badminton player and I had a great physical training today! Keep it up!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I need to be in top condition! Keep it up! Today\'s physical training was great for me!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'Just finished 2 hours of physical training? I\'m tired but happy', 'Finished my physical training for the day! Time to refuel!\r\nFinished my physical training for the day! I\'m feeling tired, but accomplished.\r\nFinished my physical training for the day! I\'m feeling sore, but satisfied.\r\nFinished my physical training for the day! I\'m feeling challenged, but determined.\r\nFinished my physical training for the day! I\'m feeling exhausted, but inspired.\r\nFinished my physical training for the day! I\'m feeling grateful, but sweaty.\r\nFinished my physical training for the day! I\'m feeling challenged, but happy.\r\nFinished my physical training for the day! I\'m feeling strong, but sweaty.\r\nFinished my physical training for the day! I\'m feeling powerful, but tired.\r\nFinished my physical training for the day! I\'m feeling grateful, but exhausted.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'Just finished this rowdy workout! I feel exhausted and energetic ?', 'Just finished this rowdy workout! I feel exhausted and energized.\r\nJust completed this vigorous workout! I feel exhausted and invigorated.\r\nFinished this intense workout! I feel exhausted and inspired.\r\nFinished this strenuous workout! I feel exhausted and motivated.\r\nJust completed this tough workout! I feel exhausted and proud.\r\nFinished this challenging workout! I feel exhausted and satisfied.\r\nFinished this hard workout! I feel exhausted and happy.\r\nJust completed this intense exercise! I feel exhausted and grateful.\r\nFinished this strenuous exercise! I feel exhausted and blessed.\r\nCompleted this tough exercise! I feel exhausted and satisfied.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'After a lovely badminton session, I feel great and refreshed. I cant wait for next time!', 'Had a great badminton session! Feeling refreshed and excited for the next one.\r\nBadminton is always a great way to refresh and energize me for the rest of the day.\r\nLove playing badminton, it always makes me feel refreshed and invigorated.\r\nBadminton is a great way to start off my day, it always leaves me feeling refreshed and energized.\r\nBadminton is a great way to workout and refresh at the same time.\r\nA great badminton session always leaves me feeling refreshed and re-energized.\r\nBadminton is a great way to relax and refresh after a long day.\r\nBadminton is a great way to start off my weekend, it always leaves me feeling refreshed and recharged.\r\nBadminton is a great way to end my day, it always leaves me feeling refreshed and relaxed.\r\nBadminton is a great way to keep me refreshed and energized throughout the day.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'Awesome badminton session with {friend}', 'Had a great badminton session with {friend} today!\r\n\r\nHad a lot of fun badmintoning with {friend} today!\r\n\r\nHad a great time playing badminton with {friend} today!\r\n\r\nHad a great time with {friend} playing badminton today!\r\n\r\nEnjoyed a fantastic badminton session with {friend} today!\r\n\r\nHad a great time badmintoning with {friend} today!\r\n\r\nHad a great time playing badminton with {friend} today!\r\n\r\nHad a great time with {friend} playing badminton today!\r\n\r\nHad an awesome badminton session with {friend} today!\r\n\r\nHad a fantastic time badmintoning with {friend} today!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Physical', 'The best part of being active is the incredible feeling you get after a tough workout ?️‍♀️', 'The best part of being active is the incredible feeling you get after a tough workout. You feel accomplished and proud of yourself!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel strong and capable!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can take on the world!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can do anything!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel refreshed and rejuvenated!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can start fresh and new!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel more motivated and inspired!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can take on any challenge!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel more confident and self-assured!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel ha', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Very good session with my coach today, it was exhausting but a great feeling to know that progress is being made', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'We thought we knew what was coming next at our session with my coach, think again! It was a super difficult practice and I am proud of myself.', 'I never knew my coach could be so tough! Practice was brutal but I learned a lot.\r\nTough practice today, but I\'m feeling stronger than ever.\r\nChallenging practice today, but I\'m more motivated than ever to get better.\r\nPractice was tough, but I\'m glad I pushed through it.\r\nIt was a tough practice, but I\'m proud of the progress I made.\r\nPractice was tough, but I\'m motivated to work harder and get better.\r\nPractice was tough, but I\'m proud of the effort I put in.\r\nPractice was tough, but I\'m grateful for the opportunity to improve.\r\nPractice was tough, but I learned a lot and I\'m ready to do better next time.\r\nPractice was tough, but I\'m proud of myself for never giving up.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'It is beyond a doubt that good technical sessions helps you to improve your badminton skills.', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Worked on some shots with my coach today. And I am getting better. ☀', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'This session was focused on my footwork. I learned a lot that will help me improve my game this season.', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Today was a good day, after a long time i felt like that. What a great badminton session i had, it all thanks to my coach and my effort.', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Practice hard so you don\'t have any regrets later on. Today, I did that with my coach.', NULL, '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Great session with coach. Worked on the running and tactics in doubles. ', 'Time well spent with my coach today - worked on my running and doubles tactics!\r\nHad a great session today with my coach - worked on my running and doubles skills!\r\nFantastic session today with my coach - worked on my running and doubles play!\r\nReally enjoyed the session today with my coach - worked on my running and doubles game!\r\nGreat session today with my coach - worked on my running and doubles strategies!\r\nSession today was great - worked on my running and doubles skills with my coach!\r\nAwesome session today - worked on my running and doubles techniques with my coach!', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Worked on badminton tactics in today\'s session. Continuing to evolve my game. ', '\r\nHad a great badminton session today! Working on my tactics and evolving my game.\r\n\r\nBadminton is a lot of fun, but it\'s also a challenging sport. I\'m always working to improve my game.\r\n\r\nGot in a great badminton session today. Always working to improve my skills.\r\n\r\nHad a great badminton workout today. Always looking to improve my game.\r\n\r\nHad a great badminton practice today. Learning new tactics and improving my skills.\r\n\r\nGot in a great badminton session today. Always looking to improve my game.\r\n\r\nHad a great badminton workout today. Always looking to improve my skills.\r\n\r\nHad a great badminton practice today. Learning new tactics and improving my game.\r\n\r\nGot in a great badminton session today. Always looking to improve my skills.\r\n\r\nHad a great badminton workout today. Always looking to improve my game.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Worked on our Badminton tactics in today\'s session: how to predict opponents movement and how to control the match.', 'Got a good workout in today while working on our badminton tactics.\r\n\r\nPracticed predicting opponents movement and controlling the match today.\r\n\r\nLearned some new badminton tactics today that I can\'t wait to try out.\r\n\r\nHad a great workout today while working on our badminton skills.\r\n\r\nWorked on our badminton skills today and learned some new tactics.\r\n\r\nGot a good workout in today while practicing our badminton techniques.\r\n\r\nWorked on our badminton techniques today and learned how to control the match.\r\n\r\nHad a great workout today while practicing our badminton skills.\r\n\r\nLearned how to control the match and predict opponents movements today.\r\n\r\nHad a great workout today while working on our badminton tactics.', '0', 'What did you focus on in your session?', 'How do you feel?'),
('Training', '', 'Technical', 'Worked on some badminton tactics today in our group session, I\'m feeling confident for the next game!', NULL, '0', NULL, NULL),
('Competit', 'What is the tournament name? > {cn}', 'I\'m trave', 'Packing up our rackets and hitting the road to the {cn}. See you there? ☀️', 'Ready to take on the best in {c}! ☀️\r\nOff to {c} to take on the best! ☀️\r\nCan\'t wait to compete in {c}! ☀️\r\nBadminton in {c} here we come! ☀️\r\nReady to compete in {cn}! ☀️\r\nHeading to {c} to compete in the {cn}! ☀️\r\nBadminton in {c}, here we come! ☀ \r\nCan\'t wait to play in the {cn}!\r\nExcited for the {cn}!\r\nReady to compete in {c}!\r\nTraveling to {c} for the {cn}!\r\nHeading to {c} for the {cn}!\r\nReady to compete in the {cn}!\r\nExcited to compete in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'In which country are you playing? > {c}', 'I\'m trave', 'The {cn}: We\'re ready to rumble! #{cn}', 'The {cn}: Ready to take on the world!\r\nThe {cn}: Bring on the competition!\r\nThe {cn}: Here we come!\r\nThe {cn}: Time to shine!\r\nThe {cn}: Let\'s do this!\r\nThe {cn}: On to the next one!\r\nThe {cn}: One step closer to the top!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your doubles partner (if any)? > {d}', 'I\'m trave', 'Some things are worth traveling a long way for. The {cn} is one of them', 'We need to create more posts here', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your mixed doubles partner (if any)? > {xd}', 'I\'m trave', 'We are looking forward to travel to play in the {cn}, hope you will support me! :)', 'Ready for some badminton action? I\'m looking forward to playing in the {cn}!\r\nI\'m excited to travel to Italy to compete in the {cn}!\r\nI\'m looking forward to playing in the {cn} and representing my country!\r\nI\'m excited to compete in the {cn} and show off my skills!\r\nI\'m looking forward to playing in the {cn} and showcasing my skills!\r\nI\'m excited to compete in the {cn} and show off my skills to the world!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Breathe deep and play strong, we’re hours away from the start of the {cn}', 'Ready, set, go!\r\nWe\'re one step closer to the {cn}\r\nWe\'re ready to take on the {cn}\r\nWe\'re ready to play our best at the {cn}\r\nWe\'re ready to take on the {cn} competition\r\nWe\'re ready to play our best at the {cn} competition\r\nWe\'re ready to show our {cn} spirit\r\nWe\'re ready to take on the {cn} competition', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'What is the tournament name? > {cn}', 'Arrived i', 'We’ve arrived in {c} and we’re ready to play badminton! ', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'In which country are you playing? > {c}', 'Arrived i', 'On my way to play badminton tournament in {c}. Can\'t wait to see you all! The adventure continues...', 'I\'m in {c} for a badminton tournament! Wish me luck!\r\nBadminton tournament in {c}? Bring it on!\r\nReady for my badminton tournament in {c}!\r\nBringing my A game to the badminton tournament in {c}!\r\nBadminton tournament in {c}? I\'m in! Off to {c} for a badminton tournament! I\'m so excited! ', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your doubles partner (if any)? > {d}', 'Arrived i', 'Here we are in {c}, looking forward to play the \'cn\' tomorrow!', 'Ready to take on {c}!\r\nExcited for the {cn} tomorrow!\r\nCan\'t wait to play in {c} tomorrow!\r\nReady to compete in the {cn}!\r\nHeading to {c} to play in the Open tomorrow!\r\nReady to compete in the {cn} tomorrow!\r\nReady to take on the {cn} tomorrow!\r\nExcited to compete in the {cn} tomorrow!\r\nReady to play in the {cn} tomorrow!\r\nReady to compete in the {cn} tomorrow!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your mixed doubles partner (if any)? > {xd}', 'Arrived i', 'I’m feeling grateful to be here in {c} for the {cn}. Look out for more updates!', 'Here at the {cn}, I\'m feeling grateful to be able to compete against some of the best players in the world.\r\nI\'m grateful to be able to compete in the {cn} and to test my skills against the best players.\r\nI\'m grateful to be able to compete in the {cn} and to learn from the best players in the world.\r\nI\'m grateful to be able to compete in the {cn} and to improve my skills against the best players.\r\nI\'m grateful to be able to compete in the {cn} and to learn from the best players in the world.\r\nI\'m grateful to be able to compete in the {cn} and to learn from the best players in the world.\r\nI\'m grateful to be able to compete in the {cn} and to improve my skills against the best players in the world.', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your mixed doubles partner (if any)? > {xd}', 'Arrived i', 'I can hardly contain my excitement. I’m in {c} to play the {cn}', 'I’ve been looking forward to this for months!\r\nI’m so excited to be in {c} for the {cn}!\r\nI’m so excited to play in the {cn}!\r\nI’m so excited to compete in the {cn}!\r\nI’m so excited to play in the {cn}!\r\nI’m so excited to compete in the {cn}!\r\nI’m so excited to play in the {cn}!\r\nI’m so excited to compete in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'What is the tournament name? > {cn}', 'Starting ', 'Ready, set, sweat! Warming up for the {cn} starting soon!', 'Getting in the zone!\r\nPumping up for the competition!\r\nReady to take on the best!\r\nFeeling the adrenaline!\r\nFocused and ready to win!\r\nTaking a break before the big match!\r\nGetting some last minute practice in!\r\nSo excited for the tournament!\r\nCan\'t wait to get started!\r\nWish me luck!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'In which country are you playing? > {c}', 'Starting ', 'Practicing for the {cn}. Here we come! ', 'Preparing for the next big tournament!\r\nGetting in some practice before the big event!\r\nWorking on our game before the {cn}!\r\nGetting ready to take on the competition in Italy!\r\nTraining hard for the next big tournament!\r\nPutting in the work to win in Italy!\r\nGetting ready to compete in the {cn}!\r\nGetting ready to take on the best in Italy!\r\nPreparing for an exciting tournament in Italy!\r\nReady to compete in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your doubles partner (if any)? > {d}', 'Starting ', 'Wish me luck! We\'re playing in the {cn} soon!', 'Time to take on the best of Italy!\r\nHere\'s to hoping I can take home the gold!\r\nReady to show everyone what I\'m made of!\r\nThis is my chance to make a name for myself in the badminton world\r\nI\'m feeling confident and ready to win!\r\nThis is my chance to make a statement in the badminton world\r\nI\'m excited to see how I stack up against the best Italy has to offer\r\nI\'m ready to take on whatever comes my way\r\nI\'m feeling confident and ready to win!\r\nI\'m excited to see how I stack up against the best Italy has to', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your mixed doubles partner (if any)? > {xd}', 'Starting ', 'Start your engines, and let the badminton begin! #{cn}', 'The {cn} is underway!\r\nThe competition is heating up at the {cn}!\r\nThe final rounds of the {cn} are underway!\r\nWho will take home the title at the {cn}?\r\nThe {cn} is a great opportunity to see the best players in action!\r\nThe final rounds of the {cn} are sure to be exciting!\r\nThe {cn} is a great opportunity to see some of the best players in the world!\r\nThe competition is fierce at the {cn}!\r\nWho will be the champion of the {cn}?\r\nThe {cn} is the perfect opportunity to see the best players in action!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your next opponent? > {opp}', 'Starting ', 'Taking on the first match tomorrow against \'player\' in the {cn}. Your support is much appreciated!', 'Time to take on my first opponent in the {cn}!\r\nI\'m so excited for this tournament!\r\nHere\'s hoping I can do well in the {cn}.\r\nWish me luck in the {cn}!\r\nReady to take on {opp} in the {cn}.\r\nCan\'t wait to start playing in the {cn}!\r\nThis is my first time playing in the {cn}.\r\nI\'m excited to see how I do in the {cn}.\r\nI\'m ready to compete in the {cn}.\r\nThanks for your support in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your next opponent? > {opp}', 'Starting ', 'First match tomorrow against {opp} in the {cn}! Can’t wait to get on court again.', 'Time to take on {opp} in the {cn}!\r\nReady to take on {opp} in the {cn}!\r\nTaking on {opp} in the {cn}!\r\nGoing up against {opp} in the {cn}!\r\nReady to take on {opp} in the {cn}!\r\nTaking on {opp} in the {cn}!\r\nGoing up against {opp} in the {cn}!\r\nTaking on {opp} in the {cn}!\r\nReady to take on {opp} in the {cn}!\r\nTaking on {opp} in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'Who is your next opponent? > {opp}', 'Starting ', 'Follow my journey in the {cn}!', 'Here I am, in the {cn}!\r\nThis is my first time in the {cn}!\r\nI\'m excited to be playing in the {cn}!\r\nI\'m looking forward to competing in the {cn}!\r\nI\'m ready for the {cn}!\r\nI\'m excited to see how I do in the {cn}!\r\nI\'m curious to see how I\'ll do in the {cn}!\r\nI\'m looking forward to playing against some of the best players in the {cn}!\r\nI\'m excited to see how I compare to the best players in the {cn}!\r\nI\'m ready to take on the best players in the {cn}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'What is the tournament name? > {cn}', 'I won a m', 'Trying to keep the momentum going after our first win of the {cn}. Here’s to another one! ??', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'So excited to have won my first match in the {cn}, here I go ???', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'We won the first match at the {cn} yesterday—I feel awesome! ?', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'It’s been a lovely morning already—I got to play some badminton ?. By the way, I won ?.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'won 1st match of the {cn}, i am feeling great ??', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'With the first win of the {cn}, I feel great', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'It\'s been quite a while since I felt so excited, motivated and focused: today I won my first match at the {cn}! ???‍♂️', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Winning my first match today in three games will bring out my confidence and determination.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Happy to win my 1st match at the {cn}, looking forward for more great wins! ?', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Just won the first match of the {cn}, and I am feeling great. The best is yet to come, let’s go for it.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Winning the 1st match of #{cn}, I feel great and energetic.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Won my first match at the {cn}! Feels great to start off the tournament strong. ', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'With the second match of the {cn} coming up, I\'m feeling great and even better after winning the game against good friend.???', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', 'Breathe in, breathe out. Focus. And that\'s how you win the first #cn badminton match!', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I won a m', NULL, NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', 'I lost my first match at the {cn} badminton tournament but I am still smiling. ☺️', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', 'I lost first match of the {cn} this morning, but it\'s all good—I had fun. ?', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', 'I lost the first match of the {cn}. I felt really bad during the game, but afterwards, I was happy and satisfied with my performance!', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', 'Hard fought match but couldn\'t make it happen today. Happy with my service, game length and strategy! So happy to have the chance to play on s', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', 'Not my best match today, but not my worst either-- I\'ll face tougher opponents ahead. I am  looking forward to what the future brings.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost but ', NULL, NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Thanks for the support in my first match at {cn} . I played an unpleasant match. Thank you everyone for supporting me!', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'I lost my match of the {cn}, played really bad though, I hope i can come back stronger next time.', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Well well, looks like I’ve just lost my first match of the {cn}', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Bad news: I lost my match of the {cn} ??? Good news: I had lots of fun playing against ...', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'My match of the {cn} Sorry to lose in straight sets ?? next time I hope so much to win ?', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Congrats to my opponent on the well fought win. Onwards and upwards ?', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'we don\'t always win but always reflect on how to win next time ???', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Disappointing loss today but back on court soon. Good luck to all, your support is amazing ??❤️', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', 'Not happy with the way I played today in my first match, especially the mental part. I need to be better and hopefully next time will be a bet', NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'Lost and ', NULL, NULL, 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'What is the tournament name? > {cn}', 'I\'m trave', 'Back home after playing the {cn}. Happy with the result. Kudos to all the players for the hard work and determination.', 'Just finished playing in the {cn}. Finished in {place} and very happy with the result. Well done to all the players for their hard work and determination! \r\nFinished the {cn}in {place} and couldn\'t be happier! A huge congratulations to all the players for their incredible effort!\r\nThrilled to have come {place} in the {cn}! A huge congratulations to all the players for their hard work and determination! \r\nSo proud to have come {place} in the {cn}! A huge congratulations to all the players! \r\nWhat an amazing experience to play in the {cn}and come in {place}! Kudos to all the players for their hard work and determination! \r\nWhat a fantastic feeling to come {place} in the {cn}! Huge congratulations to all the players! \r\nAbsolutely thrilled to have come {place} in the {cn}! Kudos to all the players for their amazing effort! \r\nSo proud of how I played in the {cn}and came in {place}! Huge congratulations to all the players! \r\nAbsolutely delighted to have come {place} in the {cn}! A big thank you to all the players for their amazing effort! \r\nThank you to all the players who competed in the {cn}! I\'m so happy with the result, {place}!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', 'What is your final standing? (example, 2nd place, top 10) > {place}', 'I\'m trave', 'Back home after a great trip to {c} to play the {cn}. Great week and Happy with the result', 'Had a great time in Italy this week playing in the {cn}. Finished in a good spot and am happy with the result!\r\nFinished the {cn} this week and am happy with how it went!\r\nPlayed in the {cn} this week and had a great time!\r\nFinished the {cn} and am feeling good about it!\r\nHad a great time in Italy this week playing in the {cn}. Finished strong and am happy with the result!\r\nFinished the {cn} this week and am feeling good about my performance!\r\nPlayed in the {cn} this week and had a great experience!\r\nFinished the {cn} and feel good about my progress!\r\nHad a great time in Italy this week playing in the {cn}Finished in a good spot and am feeling good about the experience!\r\nFinished the {cn} this week and am feeling great about it!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Back home after playing the {cn}. Happy with my result, even more excited for the future.', 'Proud of my performance at the {cn} Can\'t wait to build on this success.\r\nExcited about what the future holds after my success at the {cn}.\r\nThrilled with how I played at the {cn} I\'m looking forward to more great performances in the future.\r\nHappy that I was able to play well at the {cn} I\'m excited to see what I can achieve in the future.\r\nPleased with my result at the {cn} I\'m looking forward to more success in the future.\r\nGlad that I was able to play well at the {cn} I\'m excited to see what I can achieve in the future.\r\nProud of my accomplishment at the {cn} I\'m looking forward to more great performances in the future.\r\nProud of my performance at the {cn} I\'m excited to see what the future holds.\r\nThrilled with how I played at the {cn} I\'m looking forward to more great performances in the future.\r\nProud of my result at the {cn} I\'m excited to see what the future holds for me.', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Back home after a good week in {c}! Happy with result, I hope to play better next time. Thanks to everyone supporting me.', 'Finished my week in the {cn}! Finished {place}, looking forward to doing better next time. Thanks for all the support!\r\nHad a great week in the {cn}! Finished {place} and looking forward to doing better next time. Thanks for all the support!\r\nFinished {place} at the {cn}! Looking forward to doing better next time. Thanks to everyone for the support!\r\nHad a great time in the {cn}! Finished {place} and looking forward to doing better next time. Thanks to everyone for the support!\r\nFinished {place} at the {cn}! grateful for all the support I received. Looking forward to doing better next time!\r\nHad a great time in the {cn}! Finished {place} and grateful for all the support I received. Looking forward to doing better next time!\r\nFinished {place} at the {cn}! Thank you to everyone who supported me! I am looking forward to doing better next time!\r\nHad a great time in the {cn}! Finished {place} and thank you to everyone who supported me! I am looking forward to doing better next time!\r\nFinished {place} at the {cn}! I am grateful for all the support I received. I am looking forward to doing better next time!\r\nHad a great time in the {cn}! Finished {place} and I am grateful for all the support I received. I am looking forward to doing better next time', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Home sweet home {c flag}', 'Finally home after a long day!\r\nWhat a relief to be home!\r\nI\'m so happy to be home!\r\nI love coming home to my cozy home!\r\nHome is where the heart is!\r\nI\'m so grateful to have a home to come home to!\r\nI\'m so lucky to have a place to call home!\r\nHome is where my family is!\r\nHome is where my heart is!\r\nHome is where my happiness is!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Back home after playing the {cn}, very disappointing :(.', 'Just got back from playing in the {cn} Unfortunately, it didn\'t go as well as I\'d hoped.\r\nFinished up at the {cn} today. Disappointing performance overall.\r\nPlayed in the {cn} this week…didn\'t go as well as I had hoped.\r\nWrapping up the {cn} today. Wish things went better.\r\nThe {cn} is done and I didn\'t play well.\r\nPlayed the {cn}. Time to reflect on what went wrong.\r\nFinished up at the {cn}. Time for some self-reflection.\r\nFinished the {cn}. A lot to learn from this experience.\r\nLearned a lot at the {cn}. Now it\'s time to put that into practice.\r\nFinished up at the {cn}. Time to move on and learn from this experience.', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Hey guys! I\'m looking for funny or interesting captions for my photos. Hope you can help me! Love your suggestions!', 'Give me your best caption ideas for my next photo! \r\nLooking for funny or interesting captions for my next photo. If you have any good ideas, let me know! \r\nI need some help coming up with a funny caption for my next photo. Can you guys help me out? \r\nIf you have any good captions for my next photo, let me know! I\'m looking for something funny or interesting. \r\nI need some help with captions for my next photo. If you have any good ideas, let me know! \r\nIf you have any funny or interesting captions for my next photo, let me know! I\'d love to see them! \r\nI\'m looking for some funny or interesting captions for my next photo. If you have any good ideas, let me know! \r\nIf you have any good captions for my next photo, let me know! I\'m looking for something funny or interesting. \r\nI\'m looking for some good captions for my next photo. If you have any funny or interesting ideas, let me know! \r\nIf you have any funny or interesting captions for my next photo, let me know! I\'d love to see them!', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Happy to be back home after playing the {cn}. Not so happy with the result :(', 'Had a great time playing in the Italian Open, but unfortunately wasn\'t able to come away with a win. \r\nBack home now after a great but unsuccessful trip to the Italian Open. \r\nA tough loss at the Italian Open, but I\'m already looking forward to the next tournament. \r\nPlayed my heart out at the Italian Open, but came up short in the end. \r\nTough defeat at the Italian Open, but I\'ll learn from it and come back stronger. \r\nFinished up my time at the Italian Open with a disappointing loss. \r\nIt was a tough tournament at the Italian Open, but I learned a lot and I\'m ready for the next one. \r\nDidn\'t quite get the result I wanted at the Italian Open, but I know I can do better. \r\nFinished my time in Italy with a tough loss, but I\'ll use it as motivation to do better next time. \r\nAll in all, it was a good experience playing in the Italian Open, even though I didn\'t come away with a win.', 'tell us more!', 'Where you\'re at?', ' How do you feel'),
('Competit', '', 'I\'m trave', 'Hey guys, you bet i\'m tired now. But i realy really enjoyed the last days in {c}. Thank you so much for all your support. I\'m happy it went we', '{I\'m tired, you bet.|I\'m tired now.|You bet I\'m tired now.|I\'m tired now, you bet.|You bet I\'m tired right now.|I\'m tired right now.|Hey guys, I\'m tired now.|Do you think I\'m tired now?|You bet that I\'m tired now.|You bet I am tired now.}', 'tell us more!', 'Where you\'re at?', ' How do you feel');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;