-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 24, 2022 at 04:02 PM
-- Server version: 10.5.15-MariaDB-log
-- PHP Version: 7.4.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zppssi_blasports`
--

-- --------------------------------------------------------

--
-- Table structure for table `questions_1`
--

CREATE TABLE `questions_1` (
  `Type` varchar(8) CHARACTER SET utf8 DEFAULT NULL,
  `Q1` varchar(9) CHARACTER SET utf8 DEFAULT NULL,
  `Q2` varchar(142) CHARACTER SET utf8 DEFAULT NULL,
  `ideas` varchar(1262) CHARACTER SET utf8 DEFAULT NULL,
  `Q1_text` varchar(38) CHARACTER SET utf8 DEFAULT NULL,
  `Q2_text` varchar(16) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `questions_1`
--

INSERT INTO `questions_1` (`Type`, `Q1`, `Q2`, `ideas`, `Q1_text`, `Q2_text`) VALUES
('Training', 'Physical', 'I just finished a super-hard badminton training but it was worth it. I\'m a bit tired and I hope this weekend I can rest well.', 'I had a great training session!\r\nTough workout, but feeling accomplished!\r\nFinished my training and feeling proud!\r\nHard training session, but it was worth it!\r\nBadminton training was tough, but I\'m feeling good!\r\nFinished my training and feeling excited for the weekend!\r\nTraining was tough but I\'m feeling energized!\r\nFinished my training and feeling motivated!\r\nTraining was hard, but I\'m ready for more!\r\nFinished my training and feeling proud!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'I won’t lie — physical training is tough, but it’s the best therapy for me.', 'I love how physical training makes me feel — strong and capable.\r\nPhysical training is definitely challenging, but it\'s worth it.\r\nTraining is hard, but it\'s the best way to stay healthy and happy.\r\nI\'m grateful for physical training because it keeps me healthy and strong.\r\nPhysical training is essential for my well-being.\r\nI\'m so grateful that physical training is a part of my life.\r\nPhysical training is hard, but it\'s so worth it in the end.\r\nI love how physical training makes me feel — strong, capable, and happy.\r\nPhysical training is definitely a challenge, but it\'s worth it.\r\nTraining is hard, but it\'s the best way to stay healthy and happy.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'Hardworking can make dreams come true', 'If you want something bad enough and are willing to put in the work, you can make your dreams come true.\r\nNo matter how big your dreams may seem, if you\'re willing to work hard for them, they can become a reality.\r\nHard work is the key to making your dreams come true.\r\nDreams don\'t come true without a lot of hard work.\r\nNothing worth having comes easy. If you want your dreams to come true, you\'re going to have to work for it.\r\nThe only way to achieve your dreams is through hard work.\r\nIf you\'re willing to put in the hard work, you can make your dreams a reality.\r\nSuccess doesn\'t come easy - it takes a lot of hard work to achieve your dreams.\r\nYou have to be willing to work hard if you want your dreams to come true.\r\nHard work is the only way to make your dreams a reality.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'I might be tired but I will never give up. World class winners never quit and quitters never win!', 'Don\'t give up, no matter how tired you are. World class winners never quit and quitters never win!\r\nYou might be tired, but don\'t give up. Winners never quit and quitters never win!\r\nKeep going, no matter how tired you are. Winners never quit and quitters never win!\r\nNever give up, no matter how tired you are. Winners never quit and quitters never win!\r\nDon\'t let fatigue stop you. Winners never quit and quitters never win!\r\nDon\'t give up, no matter how exhausted you are. Winners never quit and quitters never win!\r\nYou might be tired, but don\'t give up. Winners never quit and quitters never win!\r\nKeep going, no matter how tired you are. Winners never quit and quitters never win!\r\nNever give up, no matter how tired you are. Winners never quit and quitters never win!\r\nDon\'t let fatigue stop you. Winners never quit and quitters never win!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'What a great day, I\'m quite exhausted but it\'s always worth it.', 'What a great day! I\'m exhausted but it was worth it.\r\nI had a great day! I\'m exhausted but it was worth it.\r\nI had a great day! I\'m tired but it was worth it.\r\nI had a great day! I\'m worn out but it was worth it.\r\nI had a great day! I\'m beat but it was worth it.\r\nI had a great day! I\'m pooped but it was worth it.\r\nI had a great day! I\'m spent but it was worth it.\r\nI had a great day! I\'m wiped but it was worth it.\r\nI had a great day! I\'m drained but it was worth it.\r\nI had a great day! I\'m exhausted and it was worth it.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'Just finished an exhausting yet rewarding badminton training. I like the smell of physical fitness.', 'Just finished a great badminton training! Feeling really fit now.\r\nFinished a tough badminton training session- feeling great and ready for more!\r\nTough badminton training done- feeling awesome and motivated!\r\nBadminton training was awesome- feeling really fit and motivated now!\r\nJust completed an awesome badminton training- feeling great and motivated!\r\nFinished a great badminton training- feeling really fit and motivated!\r\nBadminton training was great- feeling really fit and motivated now!\r\nJust completed an intense badminton training- feeling great and motivated!\r\nFinished an awesome badminton training- feeling really fit and motivated!\r\nBadminton training was fantastic- feeling really fit and motivated now!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'I am a badminton player, today I finished the physical training! Keep up!', 'I am a badminton player! I had a great physical training today! Keep it up!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I am always looking for ways to improve my game! Today\'s physical training was great for me!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I need to be in top condition! Today\'s physical training was great for me!\r\n\r\nI am a badminton player and I need to be in top condition! I had a great physical today!\r\n\r\nI am a badminton player and I had a great physical training today! I am always looking for ways to improve my game!\r\n\r\nI am a badminton player and I had a great physical training today! Keep it up!\r\n\r\nI had a great physical training today! I am a badminton player and I need to be in top condition!\r\n\r\nI am a badminton player and I need to be in top condition! Keep it up! Today\'s physical training was great for me!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'Just finished 2 hours of physical training? I\'m tired but happy', 'Finished my physical training for the day! Time to refuel!\r\nFinished my physical training for the day! I\'m feeling tired, but accomplished.\r\nFinished my physical training for the day! I\'m feeling sore, but satisfied.\r\nFinished my physical training for the day! I\'m feeling challenged, but determined.\r\nFinished my physical training for the day! I\'m feeling exhausted, but inspired.\r\nFinished my physical training for the day! I\'m feeling grateful, but sweaty.\r\nFinished my physical training for the day! I\'m feeling challenged, but happy.\r\nFinished my physical training for the day! I\'m feeling strong, but sweaty.\r\nFinished my physical training for the day! I\'m feeling powerful, but tired.\r\nFinished my physical training for the day! I\'m feeling grateful, but exhausted.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'Just finished this rowdy workout! I feel exhausted and energetic ?', 'Just finished this rowdy workout! I feel exhausted and energized.\r\nJust completed this vigorous workout! I feel exhausted and invigorated.\r\nFinished this intense workout! I feel exhausted and inspired.\r\nFinished this strenuous workout! I feel exhausted and motivated.\r\nJust completed this tough workout! I feel exhausted and proud.\r\nFinished this challenging workout! I feel exhausted and satisfied.\r\nFinished this hard workout! I feel exhausted and happy.\r\nJust completed this intense exercise! I feel exhausted and grateful.\r\nFinished this strenuous exercise! I feel exhausted and blessed.\r\nCompleted this tough exercise! I feel exhausted and satisfied.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'After a lovely badminton session, I feel great and refreshed. I cant wait for next time!', 'Had a great badminton session! Feeling refreshed and excited for the next one.\r\nBadminton is always a great way to refresh and energize me for the rest of the day.\r\nLove playing badminton, it always makes me feel refreshed and invigorated.\r\nBadminton is a great way to start off my day, it always leaves me feeling refreshed and energized.\r\nBadminton is a great way to workout and refresh at the same time.\r\nA great badminton session always leaves me feeling refreshed and re-energized.\r\nBadminton is a great way to relax and refresh after a long day.\r\nBadminton is a great way to start off my weekend, it always leaves me feeling refreshed and recharged.\r\nBadminton is a great way to end my day, it always leaves me feeling refreshed and relaxed.\r\nBadminton is a great way to keep me refreshed and energized throughout the day.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'Awesome badminton session with {friend}', 'Had a great badminton session with {friend} today!\r\n\r\nHad a lot of fun badmintoning with {friend} today!\r\n\r\nHad a great time playing badminton with {friend} today!\r\n\r\nHad a great time with {friend} playing badminton today!\r\n\r\nEnjoyed a fantastic badminton session with {friend} today!\r\n\r\nHad a great time badmintoning with {friend} today!\r\n\r\nHad a great time playing badminton with {friend} today!\r\n\r\nHad a great time with {friend} playing badminton today!\r\n\r\nHad an awesome badminton session with {friend} today!\r\n\r\nHad a fantastic time badmintoning with {friend} today!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Physical', 'The best part of being active is the incredible feeling you get after a tough workout ?️‍♀️', 'The best part of being active is the incredible feeling you get after a tough workout. You feel accomplished and proud of yourself!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel strong and capable!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can take on the world!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can do anything!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel refreshed and rejuvenated!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can start fresh and new!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel more motivated and inspired!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel like you can take on any challenge!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel more confident and self-assured!\r\n\r\nThe best part of being active is the incredible feeling you get after a tough workout. You feel ha', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Very good session with my coach today, it was exhausting but a great feeling to know that progress is being made', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'We thought we knew what was coming next at our session with my coach, think again! It was a super difficult practice and I am proud of myself.', 'I never knew my coach could be so tough! Practice was brutal but I learned a lot.\r\nTough practice today, but I\'m feeling stronger than ever.\r\nChallenging practice today, but I\'m more motivated than ever to get better.\r\nPractice was tough, but I\'m glad I pushed through it.\r\nIt was a tough practice, but I\'m proud of the progress I made.\r\nPractice was tough, but I\'m motivated to work harder and get better.\r\nPractice was tough, but I\'m proud of the effort I put in.\r\nPractice was tough, but I\'m grateful for the opportunity to improve.\r\nPractice was tough, but I learned a lot and I\'m ready to do better next time.\r\nPractice was tough, but I\'m proud of myself for never giving up.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'It is beyond a doubt that good technical sessions helps you to improve your badminton skills.', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Worked on some shots with my coach today. And I am getting better. ☀', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'This session was focused on my footwork. I learned a lot that will help me improve my game this season.', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Today was a good day, after a long time i felt like that. What a great badminton session i had, it all thanks to my coach and my effort.', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Practice hard so you don\'t have any regrets later on. Today, I did that with my coach.', NULL, 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Great session with coach. Worked on the running and tactics in doubles. ', 'Time well spent with my coach today - worked on my running and doubles tactics!\r\nHad a great session today with my coach - worked on my running and doubles skills!\r\nFantastic session today with my coach - worked on my running and doubles play!\r\nReally enjoyed the session today with my coach - worked on my running and doubles game!\r\nGreat session today with my coach - worked on my running and doubles strategies!\r\nSession today was great - worked on my running and doubles skills with my coach!\r\nAwesome session today - worked on my running and doubles techniques with my coach!', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Worked on badminton tactics in today\'s session. Continuing to evolve my game. ', '\r\nHad a great badminton session today! Working on my tactics and evolving my game.\r\n\r\nBadminton is a lot of fun, but it\'s also a challenging sport. I\'m always working to improve my game.\r\n\r\nGot in a great badminton session today. Always working to improve my skills.\r\n\r\nHad a great badminton workout today. Always looking to improve my game.\r\n\r\nHad a great badminton practice today. Learning new tactics and improving my skills.\r\n\r\nGot in a great badminton session today. Always looking to improve my game.\r\n\r\nHad a great badminton workout today. Always looking to improve my skills.\r\n\r\nHad a great badminton practice today. Learning new tactics and improving my game.\r\n\r\nGot in a great badminton session today. Always looking to improve my skills.\r\n\r\nHad a great badminton workout today. Always looking to improve my game.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Worked on our Badminton tactics in today\'s session: how to predict opponents movement and how to control the match.', 'Got a good workout in today while working on our badminton tactics.\r\n\r\nPracticed predicting opponents movement and controlling the match today.\r\n\r\nLearned some new badminton tactics today that I can\'t wait to try out.\r\n\r\nHad a great workout today while working on our badminton skills.\r\n\r\nWorked on our badminton skills today and learned some new tactics.\r\n\r\nGot a good workout in today while practicing our badminton techniques.\r\n\r\nWorked on our badminton techniques today and learned how to control the match.\r\n\r\nHad a great workout today while practicing our badminton skills.\r\n\r\nLearned how to control the match and predict opponents movements today.\r\n\r\nHad a great workout today while working on our badminton tactics.', 'What did you focus on in your session?', 'How do you feel?'),
('Training', 'Technical', 'Worked on some badminton tactics today in our group session, I\'m feeling confident for the next game!', NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;